// Serializes a fully-assembled ReferenceData into the three files the app
// and its Coverage Report read: src/data/reference.json (the bundled
// dataset), src/data/reference-gaps.json (gap-detection.ts's stateless
// kinds + transform/species.ts's comparative gaps, same split
// build-reference.ts used), and src/data/reference-version.ts (a baked-in
// content hash, same hashContent-based approach build-reference.ts used, so
// src/db/reference-sync.ts can compare versions without re-hashing the full
// dataset on every app boot).

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { hashContent } from "../../../src/db/content-hash";
import { detectStatelessGaps } from "../gap-detection";
import { buildComparativeGaps, FAMILY_ROOT_GAP_NOTES } from "../transform/species";
import type { ReferenceData } from "../../../src/db/reference-data";

const OUT_PATH = resolve(process.cwd(), "src/data/reference.json");
const GAPS_OUT = resolve(process.cwd(), "src/data/reference-gaps.json");
const VERSION_OUT_PATH = resolve(process.cwd(), "src/data/reference-version.ts");

export interface ReferenceJsonWriteResult {
  referenceDataVersion: string;
  staticGapsCount: number;
  comparativeGapsCount: number;
  outPath: string;
  gapsOutPath: string;
}

export function writeReferenceJson(referenceData: ReferenceData): ReferenceJsonWriteResult {
  const referenceDataJson = JSON.stringify(referenceData);
  writeFileSync(OUT_PATH, referenceDataJson);

  // Baked at build time so reference-sync.ts's "has reference.json changed
  // since last sync" check is a plain constant comparison, not a runtime
  // JSON.stringify + hash of the full dataset on every app boot.
  const referenceDataVersion = hashContent(referenceDataJson);
  writeFileSync(
    VERSION_OUT_PATH,
    `// Generated by scripts/ingest/ingest.ts — do not hand-edit.\n` +
      `// A content hash of reference.json, baked in at build time so\n` +
      `// src/db/reference-sync.ts can compare against it without re-hashing\n` +
      `// the full reference dataset on every app boot.\n` +
      `export const REFERENCE_DATA_VERSION = ${JSON.stringify(referenceDataVersion)};\n`,
  );

  const staticGaps = detectStatelessGaps(referenceData.species, referenceData.forms, referenceData.formTypes);
  const comparativeGaps = buildComparativeGaps(referenceData, FAMILY_ROOT_GAP_NOTES);
  writeFileSync(GAPS_OUT, JSON.stringify([...staticGaps, ...comparativeGaps], null, 2));

  return {
    referenceDataVersion,
    staticGapsCount: staticGaps.length,
    comparativeGapsCount: comparativeGaps.length,
    outPath: OUT_PATH,
    gapsOutPath: GAPS_OUT,
  };
}
