// Raw content of every migration SQL file under src/db/migrations/,
// embedded as string constants so they can be applied without any
// filesystem access — see migrations.ts's module comment for why.
// Generated by scripts/generate-migrations-data.ts; if a migration file
// changes or a new one is added, re-run `npm run db:generate-data` to
// regenerate this file to match — never hand-edit the object below.

export const MIGRATION_SQL_BY_TAG: Record<string, string> = {
  "0000_baseline": `-- Hand-edited after \`npm run db:generate\`: (1) restores REFERENCES clauses
-- pointing at reference tables (species, form, mega_variant, backgrounds,
-- medal, player_level), which live in src/db/schema/reference.ts and are
-- deliberately excluded from drizzle-kit's schema path. Any future
-- drizzle-kit generate that touches one of the columns below must repeat
-- this hand-edit — drizzle-kit does not know these tables exist.
-- (2) This migration deliberately encodes the schema real v6 devices
-- ALREADY HAVE on disk (TEXT timestamps) — not schema/personal.ts's final
-- INTEGER-timestamp shape. See migration 0001 for that conversion, and
-- this plan's Architecture note for why the split exists.
CREATE TABLE \`app_settings\` (
	\`key\` text PRIMARY KEY NOT NULL,
	\`value\` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`form_background_personal\` (
	\`form_slug\` text NOT NULL REFERENCES form(slug),
	\`profile_id\` integer DEFAULT 1 NOT NULL REFERENCES profile(id),
	\`achievement_field\` text NOT NULL,
	\`background_slug\` text NOT NULL REFERENCES backgrounds(slug),
	\`updated_at\` text DEFAULT '1970-01-01T00:00:00.000Z' NOT NULL,
	PRIMARY KEY(\`form_slug\`, \`achievement_field\`, \`background_slug\`)
);
--> statement-breakpoint
CREATE TABLE \`form_personal\` (
	\`form_slug\` text PRIMARY KEY NOT NULL REFERENCES form(slug),
	\`profile_id\` integer DEFAULT 1 NOT NULL REFERENCES profile(id),
	\`caught\` integer DEFAULT 0 NOT NULL,
	\`shiny\` integer DEFAULT 0 NOT NULL,
	\`floor\` integer DEFAULT 0 NOT NULL,
	\`four_star\` integer DEFAULT 0 NOT NULL,
	\`shundo\` integer DEFAULT 0 NOT NULL,
	\`lucky\` integer DEFAULT 0 NOT NULL,
	\`lucky_shiny\` integer DEFAULT 0 NOT NULL,
	\`lucky_floor\` integer DEFAULT 0 NOT NULL,
	\`lucky_four_star\` integer DEFAULT 0 NOT NULL,
	\`lucky_shundo\` integer DEFAULT 0 NOT NULL,
	\`shadow\` integer DEFAULT 0 NOT NULL,
	\`shadow_shiny\` integer DEFAULT 0 NOT NULL,
	\`shadow_floor\` integer DEFAULT 0 NOT NULL,
	\`shadow_four_star\` integer DEFAULT 0 NOT NULL,
	\`shadow_shundo\` integer DEFAULT 0 NOT NULL,
	\`dynamax\` integer DEFAULT 0 NOT NULL,
	\`dynamax_floor\` integer DEFAULT 0 NOT NULL,
	\`dynamax_shiny\` integer DEFAULT 0 NOT NULL,
	\`dynamax_four_star\` integer DEFAULT 0 NOT NULL,
	\`dynamax_shundo\` integer DEFAULT 0 NOT NULL,
	\`lucky_dynamax\` integer DEFAULT 0 NOT NULL,
	\`lucky_dynamax_floor\` integer DEFAULT 0 NOT NULL,
	\`lucky_dynamax_shiny\` integer DEFAULT 0 NOT NULL,
	\`lucky_dynamax_four_star\` integer DEFAULT 0 NOT NULL,
	\`lucky_dynamax_shundo\` integer DEFAULT 0 NOT NULL,
	\`best_shiny\` text,
	\`best_non_shiny\` text,
	\`best_lucky\` text,
	\`updated_at\` text DEFAULT '1970-01-01T00:00:00.000Z' NOT NULL,
	CONSTRAINT "form_personal_caught_bool" CHECK("form_personal"."caught" IN (0, 1)),
	CONSTRAINT "form_personal_shiny_bool" CHECK("form_personal"."shiny" IN (0, 1)),
	CONSTRAINT "form_personal_floor_bool" CHECK("form_personal"."floor" IN (0, 1)),
	CONSTRAINT "form_personal_fourStar_bool" CHECK("form_personal"."four_star" IN (0, 1)),
	CONSTRAINT "form_personal_shundo_bool" CHECK("form_personal"."shundo" IN (0, 1)),
	CONSTRAINT "form_personal_lucky_bool" CHECK("form_personal"."lucky" IN (0, 1)),
	CONSTRAINT "form_personal_luckyShiny_bool" CHECK("form_personal"."lucky_shiny" IN (0, 1)),
	CONSTRAINT "form_personal_luckyFloor_bool" CHECK("form_personal"."lucky_floor" IN (0, 1)),
	CONSTRAINT "form_personal_luckyFourStar_bool" CHECK("form_personal"."lucky_four_star" IN (0, 1)),
	CONSTRAINT "form_personal_luckyShundo_bool" CHECK("form_personal"."lucky_shundo" IN (0, 1)),
	CONSTRAINT "form_personal_shadow_bool" CHECK("form_personal"."shadow" IN (0, 1)),
	CONSTRAINT "form_personal_shadowShiny_bool" CHECK("form_personal"."shadow_shiny" IN (0, 1)),
	CONSTRAINT "form_personal_shadowFloor_bool" CHECK("form_personal"."shadow_floor" IN (0, 1)),
	CONSTRAINT "form_personal_shadowFourStar_bool" CHECK("form_personal"."shadow_four_star" IN (0, 1)),
	CONSTRAINT "form_personal_shadowShundo_bool" CHECK("form_personal"."shadow_shundo" IN (0, 1)),
	CONSTRAINT "form_personal_dynamax_bool" CHECK("form_personal"."dynamax" IN (0, 1)),
	CONSTRAINT "form_personal_dynamaxFloor_bool" CHECK("form_personal"."dynamax_floor" IN (0, 1)),
	CONSTRAINT "form_personal_dynamaxShiny_bool" CHECK("form_personal"."dynamax_shiny" IN (0, 1)),
	CONSTRAINT "form_personal_dynamaxFourStar_bool" CHECK("form_personal"."dynamax_four_star" IN (0, 1)),
	CONSTRAINT "form_personal_dynamaxShundo_bool" CHECK("form_personal"."dynamax_shundo" IN (0, 1)),
	CONSTRAINT "form_personal_luckyDynamax_bool" CHECK("form_personal"."lucky_dynamax" IN (0, 1)),
	CONSTRAINT "form_personal_luckyDynamaxFloor_bool" CHECK("form_personal"."lucky_dynamax_floor" IN (0, 1)),
	CONSTRAINT "form_personal_luckyDynamaxShiny_bool" CHECK("form_personal"."lucky_dynamax_shiny" IN (0, 1)),
	CONSTRAINT "form_personal_luckyDynamaxFourStar_bool" CHECK("form_personal"."lucky_dynamax_four_star" IN (0, 1)),
	CONSTRAINT "form_personal_luckyDynamaxShundo_bool" CHECK("form_personal"."lucky_dynamax_shundo" IN (0, 1))
);
--> statement-breakpoint
CREATE TABLE \`medal_progress_personal\` (
	\`medal_slug\` text NOT NULL REFERENCES medal(slug),
	\`profile_id\` integer DEFAULT 1 NOT NULL REFERENCES profile(id),
	\`current_rank\` integer DEFAULT 0 NOT NULL,
	\`current_count\` integer DEFAULT 0 NOT NULL,
	\`updated_at\` text NOT NULL,
	PRIMARY KEY(\`medal_slug\`, \`profile_id\`)
);
--> statement-breakpoint
CREATE TABLE \`mega_personal\` (
	\`mega_variant_slug\` text PRIMARY KEY NOT NULL REFERENCES mega_variant(slug),
	\`profile_id\` integer DEFAULT 1 NOT NULL REFERENCES profile(id),
	\`evolved\` integer DEFAULT 0 NOT NULL,
	\`shiny_evolved\` integer DEFAULT 0 NOT NULL,
	\`updated_at\` text DEFAULT '1970-01-01T00:00:00.000Z' NOT NULL,
	CONSTRAINT "mega_personal_evolved_bool" CHECK("mega_personal"."evolved" IN (0, 1)),
	CONSTRAINT "mega_personal_shinyEvolved_bool" CHECK("mega_personal"."shiny_evolved" IN (0, 1))
);
--> statement-breakpoint
CREATE TABLE \`personal_data_quarantine\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	\`source_table\` text NOT NULL,
	\`slug\` text NOT NULL,
	\`payload_json\` text NOT NULL,
	\`quarantined_at\` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`player_progress_log\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	\`profile_id\` integer DEFAULT 1 NOT NULL REFERENCES profile(id),
	\`recorded_at\` text NOT NULL,
	\`current_level\` integer,
	\`total_xp\` integer
);
--> statement-breakpoint
CREATE TABLE \`player_progress_personal\` (
	\`profile_id\` integer PRIMARY KEY NOT NULL REFERENCES profile(id),
	\`current_level\` integer REFERENCES player_level(level),
	\`total_xp\` integer,
	\`updated_at\` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`pokemon_instance\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	\`form_slug\` text NOT NULL REFERENCES form(slug),
	\`profile_id\` integer NOT NULL REFERENCES profile(id),
	\`status\` text DEFAULT 'kept' NOT NULL,
	\`recorded_at\` text NOT NULL,
	\`caught_at\` text,
	\`updated_at\` text NOT NULL,
	\`cp\` integer,
	\`iv_percent\` real,
	\`shiny\` integer DEFAULT 0 NOT NULL,
	\`lucky\` integer DEFAULT 0 NOT NULL,
	\`shadow\` integer DEFAULT 0 NOT NULL,
	\`purified\` integer DEFAULT 0 NOT NULL,
	\`hearts_earned\` integer,
	\`current_mega_level\` integer,
	\`nickname\` text,
	\`background_slug\` text REFERENCES backgrounds(slug),
	CONSTRAINT "pokemon_instance_shiny_bool" CHECK("pokemon_instance"."shiny" IN (0, 1)),
	CONSTRAINT "pokemon_instance_lucky_bool" CHECK("pokemon_instance"."lucky" IN (0, 1)),
	CONSTRAINT "pokemon_instance_shadow_bool" CHECK("pokemon_instance"."shadow" IN (0, 1)),
	CONSTRAINT "pokemon_instance_purified_bool" CHECK("pokemon_instance"."purified" IN (0, 1)),
	CONSTRAINT "pokemon_instance_status_enum" CHECK("pokemon_instance"."status" IN ('kept', 'traded', 'released', 'evolved'))
);
--> statement-breakpoint
CREATE TABLE \`pokemon_instance_max_move\` (
	\`pokemon_instance_id\` integer NOT NULL REFERENCES pokemon_instance(id),
	\`move_slot\` text NOT NULL,
	\`level\` integer,
	\`updated_at\` text NOT NULL,
	PRIMARY KEY(\`pokemon_instance_id\`, \`move_slot\`)
);
--> statement-breakpoint
CREATE TABLE \`pokemon_instance_tag\` (
	\`pokemon_instance_id\` integer NOT NULL REFERENCES pokemon_instance(id),
	\`tag_id\` integer NOT NULL REFERENCES tag(id),
	PRIMARY KEY(\`pokemon_instance_id\`, \`tag_id\`)
);
--> statement-breakpoint
CREATE TABLE \`profile\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	\`username\` text NOT NULL,
	\`friend_code\` text,
	\`created_at\` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`species_personal\` (
	\`species_slug\` text PRIMARY KEY NOT NULL REFERENCES species(slug),
	\`profile_id\` integer DEFAULT 1 NOT NULL REFERENCES profile(id),
	\`registered\` integer DEFAULT 0 NOT NULL,
	\`xxl\` integer DEFAULT 0 NOT NULL,
	\`xxs\` integer DEFAULT 0 NOT NULL,
	\`purified\` integer DEFAULT 0 NOT NULL,
	\`updated_at\` text DEFAULT '1970-01-01T00:00:00.000Z' NOT NULL,
	CONSTRAINT "species_personal_registered_bool" CHECK("species_personal"."registered" IN (0, 1)),
	CONSTRAINT "species_personal_xxl_bool" CHECK("species_personal"."xxl" IN (0, 1)),
	CONSTRAINT "species_personal_xxs_bool" CHECK("species_personal"."xxs" IN (0, 1)),
	CONSTRAINT "species_personal_purified_bool" CHECK("species_personal"."purified" IN (0, 1))
);
--> statement-breakpoint
CREATE TABLE \`tag\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	\`profile_id\` integer NOT NULL REFERENCES profile(id),
	\`name\` text NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`tag_profile_id_name_unique\` ON \`tag\` (\`profile_id\`,\`name\`);`,
  "0001_timestamps_to_epoch_ms": `-- Hand-edited after \`npm run db:generate\`: (1) restores REFERENCES clauses
-- lost by this rebuild, per 0000_baseline.sql's header comment ("any future
-- drizzle-kit generate that touches one of the columns below must repeat
-- this hand-edit") — this migration's table-rebuild recreates every column
-- that carries a REFERENCES clause in 0000 except profile/personal_data_
-- quarantine (which get none there either). (2) Converts every TEXT
-- timestamp column's INSERT...SELECT expression to the julianday-based
-- epoch-ms conversion below, instead of drizzle-kit's plain column copy.
-- (3) Moves drizzle-kit's own \`PRAGMA foreign_keys=ON\` from right after the
-- FIRST rebuilt table (form_background_personal) to the very end of this
-- file, after every table has been rebuilt. As generated, drizzle-kit only
-- wrapped the first table in OFF/ON and left FK enforcement ON for the
-- remaining nine — but src/data/sqlite-repository.ts runs
-- runPersonalMigrations() (this migration) BEFORE syncReferenceData()
-- creates the reference tables (species, form, mega_variant, backgrounds,
-- medal, player_level) these REFERENCES clauses point at. SQLite validates
-- a REFERENCES target's existence at INSERT-time whenever foreign_keys=ON,
-- regardless of row count — so with drizzle-kit's original bracketing this
-- migration throws "no such table: main.form" (etc.) on every table after
-- the first, on every fresh install and every real upgrade. Verified
-- empirically with the sqlite3 CLI before and after this fix. NOTE: this
-- file's own PRAGMA statements are inert once run through the app's real
-- migration runner (src/db/migrations.ts wraps every pending migration's
-- statements in one transaction, and PRAGMA foreign_keys is a documented
-- no-op inside an active transaction) — the runner itself toggles this
-- PRAGMA outside that transaction instead. These statements remain here,
-- correct and self-documenting, for anyone applying this file standalone
-- (e.g. via the sqlite3 CLI) outside that runner.
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE \`__new_form_background_personal\` (
	\`form_slug\` text NOT NULL REFERENCES form(slug),
	\`profile_id\` integer DEFAULT 1 NOT NULL REFERENCES profile(id),
	\`achievement_field\` text NOT NULL,
	\`background_slug\` text NOT NULL REFERENCES backgrounds(slug),
	\`updated_at\` integer DEFAULT 0 NOT NULL,
	PRIMARY KEY(\`form_slug\`, \`achievement_field\`, \`background_slug\`)
);
--> statement-breakpoint
INSERT INTO \`__new_form_background_personal\`("form_slug", "profile_id", "achievement_field", "background_slug", "updated_at")
  SELECT "form_slug", "profile_id", "achievement_field", "background_slug",
         CAST(ROUND((julianday("updated_at") - 2440587.5) * 86400000) AS INTEGER)
  FROM \`form_background_personal\`;--> statement-breakpoint
DROP TABLE \`form_background_personal\`;--> statement-breakpoint
ALTER TABLE \`__new_form_background_personal\` RENAME TO \`form_background_personal\`;--> statement-breakpoint
CREATE TABLE \`__new_form_personal\` (
	\`form_slug\` text PRIMARY KEY NOT NULL REFERENCES form(slug),
	\`profile_id\` integer DEFAULT 1 NOT NULL REFERENCES profile(id),
	\`caught\` integer DEFAULT false NOT NULL,
	\`shiny\` integer DEFAULT false NOT NULL,
	\`floor\` integer DEFAULT false NOT NULL,
	\`four_star\` integer DEFAULT false NOT NULL,
	\`shundo\` integer DEFAULT false NOT NULL,
	\`lucky\` integer DEFAULT false NOT NULL,
	\`lucky_shiny\` integer DEFAULT false NOT NULL,
	\`lucky_floor\` integer DEFAULT false NOT NULL,
	\`lucky_four_star\` integer DEFAULT false NOT NULL,
	\`lucky_shundo\` integer DEFAULT false NOT NULL,
	\`shadow\` integer DEFAULT false NOT NULL,
	\`shadow_shiny\` integer DEFAULT false NOT NULL,
	\`shadow_floor\` integer DEFAULT false NOT NULL,
	\`shadow_four_star\` integer DEFAULT false NOT NULL,
	\`shadow_shundo\` integer DEFAULT false NOT NULL,
	\`dynamax\` integer DEFAULT false NOT NULL,
	\`dynamax_floor\` integer DEFAULT false NOT NULL,
	\`dynamax_shiny\` integer DEFAULT false NOT NULL,
	\`dynamax_four_star\` integer DEFAULT false NOT NULL,
	\`dynamax_shundo\` integer DEFAULT false NOT NULL,
	\`lucky_dynamax\` integer DEFAULT false NOT NULL,
	\`lucky_dynamax_floor\` integer DEFAULT false NOT NULL,
	\`lucky_dynamax_shiny\` integer DEFAULT false NOT NULL,
	\`lucky_dynamax_four_star\` integer DEFAULT false NOT NULL,
	\`lucky_dynamax_shundo\` integer DEFAULT false NOT NULL,
	\`best_shiny\` text,
	\`best_non_shiny\` text,
	\`best_lucky\` text,
	\`updated_at\` integer DEFAULT 0 NOT NULL,
	CONSTRAINT "form_personal_caught_bool" CHECK("__new_form_personal"."caught" IN (0, 1)),
	CONSTRAINT "form_personal_shiny_bool" CHECK("__new_form_personal"."shiny" IN (0, 1)),
	CONSTRAINT "form_personal_floor_bool" CHECK("__new_form_personal"."floor" IN (0, 1)),
	CONSTRAINT "form_personal_fourStar_bool" CHECK("__new_form_personal"."four_star" IN (0, 1)),
	CONSTRAINT "form_personal_shundo_bool" CHECK("__new_form_personal"."shundo" IN (0, 1)),
	CONSTRAINT "form_personal_lucky_bool" CHECK("__new_form_personal"."lucky" IN (0, 1)),
	CONSTRAINT "form_personal_luckyShiny_bool" CHECK("__new_form_personal"."lucky_shiny" IN (0, 1)),
	CONSTRAINT "form_personal_luckyFloor_bool" CHECK("__new_form_personal"."lucky_floor" IN (0, 1)),
	CONSTRAINT "form_personal_luckyFourStar_bool" CHECK("__new_form_personal"."lucky_four_star" IN (0, 1)),
	CONSTRAINT "form_personal_luckyShundo_bool" CHECK("__new_form_personal"."lucky_shundo" IN (0, 1)),
	CONSTRAINT "form_personal_shadow_bool" CHECK("__new_form_personal"."shadow" IN (0, 1)),
	CONSTRAINT "form_personal_shadowShiny_bool" CHECK("__new_form_personal"."shadow_shiny" IN (0, 1)),
	CONSTRAINT "form_personal_shadowFloor_bool" CHECK("__new_form_personal"."shadow_floor" IN (0, 1)),
	CONSTRAINT "form_personal_shadowFourStar_bool" CHECK("__new_form_personal"."shadow_four_star" IN (0, 1)),
	CONSTRAINT "form_personal_shadowShundo_bool" CHECK("__new_form_personal"."shadow_shundo" IN (0, 1)),
	CONSTRAINT "form_personal_dynamax_bool" CHECK("__new_form_personal"."dynamax" IN (0, 1)),
	CONSTRAINT "form_personal_dynamaxFloor_bool" CHECK("__new_form_personal"."dynamax_floor" IN (0, 1)),
	CONSTRAINT "form_personal_dynamaxShiny_bool" CHECK("__new_form_personal"."dynamax_shiny" IN (0, 1)),
	CONSTRAINT "form_personal_dynamaxFourStar_bool" CHECK("__new_form_personal"."dynamax_four_star" IN (0, 1)),
	CONSTRAINT "form_personal_dynamaxShundo_bool" CHECK("__new_form_personal"."dynamax_shundo" IN (0, 1)),
	CONSTRAINT "form_personal_luckyDynamax_bool" CHECK("__new_form_personal"."lucky_dynamax" IN (0, 1)),
	CONSTRAINT "form_personal_luckyDynamaxFloor_bool" CHECK("__new_form_personal"."lucky_dynamax_floor" IN (0, 1)),
	CONSTRAINT "form_personal_luckyDynamaxShiny_bool" CHECK("__new_form_personal"."lucky_dynamax_shiny" IN (0, 1)),
	CONSTRAINT "form_personal_luckyDynamaxFourStar_bool" CHECK("__new_form_personal"."lucky_dynamax_four_star" IN (0, 1)),
	CONSTRAINT "form_personal_luckyDynamaxShundo_bool" CHECK("__new_form_personal"."lucky_dynamax_shundo" IN (0, 1))
);
--> statement-breakpoint
INSERT INTO \`__new_form_personal\`("form_slug", "profile_id", "caught", "shiny", "floor", "four_star", "shundo", "lucky", "lucky_shiny", "lucky_floor", "lucky_four_star", "lucky_shundo", "shadow", "shadow_shiny", "shadow_floor", "shadow_four_star", "shadow_shundo", "dynamax", "dynamax_floor", "dynamax_shiny", "dynamax_four_star", "dynamax_shundo", "lucky_dynamax", "lucky_dynamax_floor", "lucky_dynamax_shiny", "lucky_dynamax_four_star", "lucky_dynamax_shundo", "best_shiny", "best_non_shiny", "best_lucky", "updated_at")
  SELECT "form_slug", "profile_id", "caught", "shiny", "floor", "four_star", "shundo", "lucky", "lucky_shiny", "lucky_floor", "lucky_four_star", "lucky_shundo", "shadow", "shadow_shiny", "shadow_floor", "shadow_four_star", "shadow_shundo", "dynamax", "dynamax_floor", "dynamax_shiny", "dynamax_four_star", "dynamax_shundo", "lucky_dynamax", "lucky_dynamax_floor", "lucky_dynamax_shiny", "lucky_dynamax_four_star", "lucky_dynamax_shundo", "best_shiny", "best_non_shiny", "best_lucky",
         CAST(ROUND((julianday("updated_at") - 2440587.5) * 86400000) AS INTEGER)
  FROM \`form_personal\`;--> statement-breakpoint
DROP TABLE \`form_personal\`;--> statement-breakpoint
ALTER TABLE \`__new_form_personal\` RENAME TO \`form_personal\`;--> statement-breakpoint
CREATE TABLE \`__new_medal_progress_personal\` (
	\`medal_slug\` text NOT NULL REFERENCES medal(slug),
	\`profile_id\` integer DEFAULT 1 NOT NULL REFERENCES profile(id),
	\`current_rank\` integer DEFAULT 0 NOT NULL,
	\`current_count\` integer DEFAULT 0 NOT NULL,
	\`updated_at\` integer NOT NULL,
	PRIMARY KEY(\`medal_slug\`, \`profile_id\`)
);
--> statement-breakpoint
INSERT INTO \`__new_medal_progress_personal\`("medal_slug", "profile_id", "current_rank", "current_count", "updated_at")
  SELECT "medal_slug", "profile_id", "current_rank", "current_count",
         CAST(ROUND((julianday("updated_at") - 2440587.5) * 86400000) AS INTEGER)
  FROM \`medal_progress_personal\`;--> statement-breakpoint
DROP TABLE \`medal_progress_personal\`;--> statement-breakpoint
ALTER TABLE \`__new_medal_progress_personal\` RENAME TO \`medal_progress_personal\`;--> statement-breakpoint
CREATE TABLE \`__new_mega_personal\` (
	\`mega_variant_slug\` text PRIMARY KEY NOT NULL REFERENCES mega_variant(slug),
	\`profile_id\` integer DEFAULT 1 NOT NULL REFERENCES profile(id),
	\`evolved\` integer DEFAULT false NOT NULL,
	\`shiny_evolved\` integer DEFAULT false NOT NULL,
	\`updated_at\` integer DEFAULT 0 NOT NULL,
	CONSTRAINT "mega_personal_evolved_bool" CHECK("__new_mega_personal"."evolved" IN (0, 1)),
	CONSTRAINT "mega_personal_shinyEvolved_bool" CHECK("__new_mega_personal"."shiny_evolved" IN (0, 1))
);
--> statement-breakpoint
INSERT INTO \`__new_mega_personal\`("mega_variant_slug", "profile_id", "evolved", "shiny_evolved", "updated_at")
  SELECT "mega_variant_slug", "profile_id", "evolved", "shiny_evolved",
         CAST(ROUND((julianday("updated_at") - 2440587.5) * 86400000) AS INTEGER)
  FROM \`mega_personal\`;--> statement-breakpoint
DROP TABLE \`mega_personal\`;--> statement-breakpoint
ALTER TABLE \`__new_mega_personal\` RENAME TO \`mega_personal\`;--> statement-breakpoint
CREATE TABLE \`__new_personal_data_quarantine\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	\`source_table\` text NOT NULL,
	\`slug\` text NOT NULL,
	\`payload_json\` text NOT NULL,
	\`quarantined_at\` integer NOT NULL
);
--> statement-breakpoint
INSERT INTO \`__new_personal_data_quarantine\`("id", "source_table", "slug", "payload_json", "quarantined_at")
  SELECT "id", "source_table", "slug", "payload_json",
         CAST(ROUND((julianday("quarantined_at") - 2440587.5) * 86400000) AS INTEGER)
  FROM \`personal_data_quarantine\`;--> statement-breakpoint
DROP TABLE \`personal_data_quarantine\`;--> statement-breakpoint
ALTER TABLE \`__new_personal_data_quarantine\` RENAME TO \`personal_data_quarantine\`;--> statement-breakpoint
CREATE TABLE \`__new_player_progress_log\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	\`profile_id\` integer DEFAULT 1 NOT NULL REFERENCES profile(id),
	\`recorded_at\` integer NOT NULL,
	\`current_level\` integer,
	\`total_xp\` integer
);
--> statement-breakpoint
INSERT INTO \`__new_player_progress_log\`("id", "profile_id", "recorded_at", "current_level", "total_xp")
  SELECT "id", "profile_id",
         CAST(ROUND((julianday("recorded_at") - 2440587.5) * 86400000) AS INTEGER),
         "current_level", "total_xp"
  FROM \`player_progress_log\`;--> statement-breakpoint
DROP TABLE \`player_progress_log\`;--> statement-breakpoint
ALTER TABLE \`__new_player_progress_log\` RENAME TO \`player_progress_log\`;--> statement-breakpoint
CREATE TABLE \`__new_player_progress_personal\` (
	\`profile_id\` integer PRIMARY KEY NOT NULL REFERENCES profile(id),
	\`current_level\` integer REFERENCES player_level(level),
	\`total_xp\` integer,
	\`updated_at\` integer NOT NULL
);
--> statement-breakpoint
INSERT INTO \`__new_player_progress_personal\`("profile_id", "current_level", "total_xp", "updated_at")
  SELECT "profile_id", "current_level", "total_xp",
         CAST(ROUND((julianday("updated_at") - 2440587.5) * 86400000) AS INTEGER)
  FROM \`player_progress_personal\`;--> statement-breakpoint
DROP TABLE \`player_progress_personal\`;--> statement-breakpoint
ALTER TABLE \`__new_player_progress_personal\` RENAME TO \`player_progress_personal\`;--> statement-breakpoint
CREATE TABLE \`__new_pokemon_instance\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	\`form_slug\` text NOT NULL REFERENCES form(slug),
	\`profile_id\` integer NOT NULL REFERENCES profile(id),
	\`status\` text DEFAULT 'kept' NOT NULL,
	\`recorded_at\` integer NOT NULL,
	\`caught_at\` integer,
	\`updated_at\` integer NOT NULL,
	\`cp\` integer,
	\`iv_percent\` real,
	\`shiny\` integer DEFAULT false NOT NULL,
	\`lucky\` integer DEFAULT false NOT NULL,
	\`shadow\` integer DEFAULT false NOT NULL,
	\`purified\` integer DEFAULT false NOT NULL,
	\`hearts_earned\` integer,
	\`current_mega_level\` integer,
	\`nickname\` text,
	\`background_slug\` text REFERENCES backgrounds(slug),
	CONSTRAINT "pokemon_instance_shiny_bool" CHECK("__new_pokemon_instance"."shiny" IN (0, 1)),
	CONSTRAINT "pokemon_instance_lucky_bool" CHECK("__new_pokemon_instance"."lucky" IN (0, 1)),
	CONSTRAINT "pokemon_instance_shadow_bool" CHECK("__new_pokemon_instance"."shadow" IN (0, 1)),
	CONSTRAINT "pokemon_instance_purified_bool" CHECK("__new_pokemon_instance"."purified" IN (0, 1)),
	CONSTRAINT "pokemon_instance_status_enum" CHECK("__new_pokemon_instance"."status" IN ('kept', 'traded', 'released', 'evolved'))
);
--> statement-breakpoint
INSERT INTO \`__new_pokemon_instance\`("id", "form_slug", "profile_id", "status", "recorded_at", "caught_at", "updated_at", "cp", "iv_percent", "shiny", "lucky", "shadow", "purified", "hearts_earned", "current_mega_level", "nickname", "background_slug")
  SELECT "id", "form_slug", "profile_id", "status",
         CAST(ROUND((julianday("recorded_at") - 2440587.5) * 86400000) AS INTEGER),
         CAST(ROUND((julianday("caught_at") - 2440587.5) * 86400000) AS INTEGER),
         CAST(ROUND((julianday("updated_at") - 2440587.5) * 86400000) AS INTEGER),
         "cp", "iv_percent", "shiny", "lucky", "shadow", "purified", "hearts_earned", "current_mega_level", "nickname", "background_slug"
  FROM \`pokemon_instance\`;--> statement-breakpoint
DROP TABLE \`pokemon_instance\`;--> statement-breakpoint
ALTER TABLE \`__new_pokemon_instance\` RENAME TO \`pokemon_instance\`;--> statement-breakpoint
CREATE TABLE \`__new_pokemon_instance_max_move\` (
	\`pokemon_instance_id\` integer NOT NULL REFERENCES pokemon_instance(id),
	\`move_slot\` text NOT NULL,
	\`level\` integer,
	\`updated_at\` integer NOT NULL,
	PRIMARY KEY(\`pokemon_instance_id\`, \`move_slot\`)
);
--> statement-breakpoint
INSERT INTO \`__new_pokemon_instance_max_move\`("pokemon_instance_id", "move_slot", "level", "updated_at")
  SELECT "pokemon_instance_id", "move_slot", "level",
         CAST(ROUND((julianday("updated_at") - 2440587.5) * 86400000) AS INTEGER)
  FROM \`pokemon_instance_max_move\`;--> statement-breakpoint
DROP TABLE \`pokemon_instance_max_move\`;--> statement-breakpoint
ALTER TABLE \`__new_pokemon_instance_max_move\` RENAME TO \`pokemon_instance_max_move\`;--> statement-breakpoint
CREATE TABLE \`__new_profile\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	\`username\` text NOT NULL,
	\`friend_code\` text,
	\`created_at\` integer NOT NULL
);
--> statement-breakpoint
INSERT INTO \`__new_profile\`("id", "username", "friend_code", "created_at")
  SELECT "id", "username", "friend_code",
         CAST(ROUND((julianday("created_at") - 2440587.5) * 86400000) AS INTEGER)
  FROM \`profile\`;--> statement-breakpoint
DROP TABLE \`profile\`;--> statement-breakpoint
ALTER TABLE \`__new_profile\` RENAME TO \`profile\`;--> statement-breakpoint
CREATE TABLE \`__new_species_personal\` (
	\`species_slug\` text PRIMARY KEY NOT NULL REFERENCES species(slug),
	\`profile_id\` integer DEFAULT 1 NOT NULL REFERENCES profile(id),
	\`registered\` integer DEFAULT false NOT NULL,
	\`xxl\` integer DEFAULT false NOT NULL,
	\`xxs\` integer DEFAULT false NOT NULL,
	\`purified\` integer DEFAULT false NOT NULL,
	\`updated_at\` integer DEFAULT 0 NOT NULL,
	CONSTRAINT "species_personal_registered_bool" CHECK("__new_species_personal"."registered" IN (0, 1)),
	CONSTRAINT "species_personal_xxl_bool" CHECK("__new_species_personal"."xxl" IN (0, 1)),
	CONSTRAINT "species_personal_xxs_bool" CHECK("__new_species_personal"."xxs" IN (0, 1)),
	CONSTRAINT "species_personal_purified_bool" CHECK("__new_species_personal"."purified" IN (0, 1))
);
--> statement-breakpoint
INSERT INTO \`__new_species_personal\`("species_slug", "profile_id", "registered", "xxl", "xxs", "purified", "updated_at")
  SELECT "species_slug", "profile_id", "registered", "xxl", "xxs", "purified",
         CAST(ROUND((julianday("updated_at") - 2440587.5) * 86400000) AS INTEGER)
  FROM \`species_personal\`;--> statement-breakpoint
DROP TABLE \`species_personal\`;--> statement-breakpoint
ALTER TABLE \`__new_species_personal\` RENAME TO \`species_personal\`;--> statement-breakpoint
PRAGMA foreign_keys=ON;
`,
  "0002_messy_killraven": `-- Hand-edited after \`npm run db:generate\`, per 0000_baseline.sql's header
-- comment ("any future drizzle-kit generate that touches one of the columns
-- below must repeat this hand-edit") and 0001_timestamps_to_epoch_ms.sql's
-- header comment (same reasoning, applied there to a ten-table rebuild).
-- Two fixes were needed here, both verified empirically with the sqlite3
-- CLI against a throwaway file DB before and after:
--
-- (1) Restored the REFERENCES clauses on \`form_slug\` (-> form(slug)),
-- \`profile_id\` (-> profile(id)), and \`background_slug\` (-> backgrounds(slug))
-- that drizzle-kit's rebuild drops, because those clauses were hand-added to
-- earlier migrations and were never present on the Drizzle schema objects
-- themselves (\`formSlug\`/\`profileId\`/\`backgroundSlug\` in
-- src/db/schema/personal.ts carry no \`.references()\` call).
--
-- (2) drizzle-kit's raw INSERT...SELECT for the table-rebuild both (a) tried
-- to SELECT "iv_attack", "iv_defense", "iv_stamina" from the *old*
-- \`pokemon_instance\` table, which doesn't have those columns yet (this
-- migration is what introduces them) -- confirmed empirically: this raises
-- "no such column: iv_attack" -- and (b) listed "iv_percent" as an INSERT
-- target column, which SQLite rejects outright for a GENERATED column --
-- confirmed empirically: "cannot INSERT into generated column iv_percent".
-- Fixed by dropping all four columns from both the INSERT column list and
-- the SELECT list; iv_attack/iv_defense/iv_stamina land NULL (their column
-- default) for every pre-existing row, and iv_percent is computed by SQLite
-- itself from those (NULL, per its CASE expression) on read.
--
-- This migration only touches one table, so unlike 0001 there is no
-- multi-table FK-ordering hazard to fix: drizzle-kit's OFF-before/ON-after
-- bracketing around this single CREATE/INSERT/DROP/RENAME sequence is
-- already correct as generated -- confirmed empirically by applying the
-- rest of this file unmodified (REFERENCES targets pre-exist from earlier
-- migrations by the time this one runs).
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE \`__new_pokemon_instance\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	\`form_slug\` text NOT NULL REFERENCES form(slug),
	\`profile_id\` integer NOT NULL REFERENCES profile(id),
	\`status\` text DEFAULT 'kept' NOT NULL,
	\`recorded_at\` integer NOT NULL,
	\`caught_at\` integer,
	\`updated_at\` integer NOT NULL,
	\`cp\` integer,
	\`iv_attack\` integer,
	\`iv_defense\` integer,
	\`iv_stamina\` integer,
	\`iv_percent\` real GENERATED ALWAYS AS (CASE WHEN iv_attack IS NOT NULL AND iv_defense IS NOT NULL AND iv_stamina IS NOT NULL THEN ROUND((iv_attack + iv_defense + iv_stamina) * 100.0 / 45, 1) ELSE NULL END) VIRTUAL,
	\`shiny\` integer DEFAULT false NOT NULL,
	\`lucky\` integer DEFAULT false NOT NULL,
	\`shadow\` integer DEFAULT false NOT NULL,
	\`purified\` integer DEFAULT false NOT NULL,
	\`hearts_earned\` integer,
	\`current_mega_level\` integer,
	\`nickname\` text,
	\`background_slug\` text REFERENCES backgrounds(slug),
	CONSTRAINT "pokemon_instance_shiny_bool" CHECK("__new_pokemon_instance"."shiny" IN (0, 1)),
	CONSTRAINT "pokemon_instance_lucky_bool" CHECK("__new_pokemon_instance"."lucky" IN (0, 1)),
	CONSTRAINT "pokemon_instance_shadow_bool" CHECK("__new_pokemon_instance"."shadow" IN (0, 1)),
	CONSTRAINT "pokemon_instance_purified_bool" CHECK("__new_pokemon_instance"."purified" IN (0, 1)),
	CONSTRAINT "pokemon_instance_status_enum" CHECK("__new_pokemon_instance"."status" IN ('kept', 'traded', 'released', 'evolved')),
	CONSTRAINT "pokemon_instance_iv_attack_range" CHECK("__new_pokemon_instance"."iv_attack" IS NULL OR ("__new_pokemon_instance"."iv_attack" >= 0 AND "__new_pokemon_instance"."iv_attack" <= 15)),
	CONSTRAINT "pokemon_instance_iv_defense_range" CHECK("__new_pokemon_instance"."iv_defense" IS NULL OR ("__new_pokemon_instance"."iv_defense" >= 0 AND "__new_pokemon_instance"."iv_defense" <= 15)),
	CONSTRAINT "pokemon_instance_iv_stamina_range" CHECK("__new_pokemon_instance"."iv_stamina" IS NULL OR ("__new_pokemon_instance"."iv_stamina" >= 0 AND "__new_pokemon_instance"."iv_stamina" <= 15))
);
--> statement-breakpoint
INSERT INTO \`__new_pokemon_instance\`("id", "form_slug", "profile_id", "status", "recorded_at", "caught_at", "updated_at", "cp", "shiny", "lucky", "shadow", "purified", "hearts_earned", "current_mega_level", "nickname", "background_slug") SELECT "id", "form_slug", "profile_id", "status", "recorded_at", "caught_at", "updated_at", "cp", "shiny", "lucky", "shadow", "purified", "hearts_earned", "current_mega_level", "nickname", "background_slug" FROM \`pokemon_instance\`;--> statement-breakpoint
DROP TABLE \`pokemon_instance\`;--> statement-breakpoint
ALTER TABLE \`__new_pokemon_instance\` RENAME TO \`pokemon_instance\`;--> statement-breakpoint
PRAGMA foreign_keys=ON;
`,
  "0003_familiar_meggan": `-- Hand-edited after \`npm run db:generate\`, per 0000_baseline.sql's header
-- comment and the precedent in 0002_messy_killraven.sql (same table, same
-- two issues, same fixes):
--
-- (1) Restored the REFERENCES clauses on \`form_slug\` (-> form(slug)),
-- \`profile_id\` (-> profile(id)), and \`background_slug\` (-> backgrounds(slug))
-- that drizzle-kit's rebuild drops, because those clauses were hand-added to
-- earlier migrations and were never present on the Drizzle schema objects
-- themselves (\`formSlug\`/\`profileId\`/\`backgroundSlug\` in
-- src/db/schema/personal.ts carry no \`.references()\` call).
--
-- (2) drizzle-kit's raw INSERT...SELECT for the table-rebuild both (a)
-- listed "iv_percent" as an INSERT target column, which SQLite rejects
-- outright for a GENERATED column -- confirmed empirically: "cannot INSERT
-- into generated column iv_percent" (same issue as
-- 0002_messy_killraven.sql) -- and (b) tried to SELECT "dynamax" and
-- "received_via_trade" from the *old* pokemon_instance table, which doesn't
-- have those columns yet (this migration is what introduces them) --
-- confirmed empirically: "no such column: dynamax" (same class of issue as
-- 0002's iv_attack/iv_defense/iv_stamina fix). Fixed by dropping all three
-- columns from both the INSERT column list and the SELECT list; iv_percent
-- is computed by SQLite itself on read, and dynamax/received_via_trade land
-- their column default (false) for every pre-existing row via SQLite's
-- normal DEFAULT-on-omitted-column behavior.
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE \`__new_pokemon_instance\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	\`form_slug\` text NOT NULL REFERENCES form(slug),
	\`profile_id\` integer NOT NULL REFERENCES profile(id),
	\`status\` text DEFAULT 'kept' NOT NULL,
	\`recorded_at\` integer NOT NULL,
	\`caught_at\` integer,
	\`updated_at\` integer NOT NULL,
	\`cp\` integer,
	\`iv_attack\` integer,
	\`iv_defense\` integer,
	\`iv_stamina\` integer,
	\`iv_percent\` real GENERATED ALWAYS AS (CASE WHEN iv_attack IS NOT NULL AND iv_defense IS NOT NULL AND iv_stamina IS NOT NULL THEN ROUND((iv_attack + iv_defense + iv_stamina) * 100.0 / 45, 1) ELSE NULL END) VIRTUAL,
	\`shiny\` integer DEFAULT false NOT NULL,
	\`lucky\` integer DEFAULT false NOT NULL,
	\`shadow\` integer DEFAULT false NOT NULL,
	\`purified\` integer DEFAULT false NOT NULL,
	\`dynamax\` integer DEFAULT false NOT NULL,
	\`received_via_trade\` integer DEFAULT false NOT NULL,
	\`hearts_earned\` integer,
	\`current_mega_level\` integer,
	\`nickname\` text,
	\`background_slug\` text REFERENCES backgrounds(slug),
	CONSTRAINT "pokemon_instance_shiny_bool" CHECK("__new_pokemon_instance"."shiny" IN (0, 1)),
	CONSTRAINT "pokemon_instance_lucky_bool" CHECK("__new_pokemon_instance"."lucky" IN (0, 1)),
	CONSTRAINT "pokemon_instance_shadow_bool" CHECK("__new_pokemon_instance"."shadow" IN (0, 1)),
	CONSTRAINT "pokemon_instance_purified_bool" CHECK("__new_pokemon_instance"."purified" IN (0, 1)),
	CONSTRAINT "pokemon_instance_dynamax_bool" CHECK("__new_pokemon_instance"."dynamax" IN (0, 1)),
	CONSTRAINT "pokemon_instance_receivedViaTrade_bool" CHECK("__new_pokemon_instance"."received_via_trade" IN (0, 1)),
	CONSTRAINT "pokemon_instance_status_enum" CHECK("__new_pokemon_instance"."status" IN ('kept', 'traded', 'released', 'evolved')),
	CONSTRAINT "pokemon_instance_iv_attack_range" CHECK("__new_pokemon_instance"."iv_attack" IS NULL OR ("__new_pokemon_instance"."iv_attack" >= 0 AND "__new_pokemon_instance"."iv_attack" <= 15)),
	CONSTRAINT "pokemon_instance_iv_defense_range" CHECK("__new_pokemon_instance"."iv_defense" IS NULL OR ("__new_pokemon_instance"."iv_defense" >= 0 AND "__new_pokemon_instance"."iv_defense" <= 15)),
	CONSTRAINT "pokemon_instance_iv_stamina_range" CHECK("__new_pokemon_instance"."iv_stamina" IS NULL OR ("__new_pokemon_instance"."iv_stamina" >= 0 AND "__new_pokemon_instance"."iv_stamina" <= 15))
);
--> statement-breakpoint
INSERT INTO \`__new_pokemon_instance\`("id", "form_slug", "profile_id", "status", "recorded_at", "caught_at", "updated_at", "cp", "iv_attack", "iv_defense", "iv_stamina", "shiny", "lucky", "shadow", "purified", "hearts_earned", "current_mega_level", "nickname", "background_slug") SELECT "id", "form_slug", "profile_id", "status", "recorded_at", "caught_at", "updated_at", "cp", "iv_attack", "iv_defense", "iv_stamina", "shiny", "lucky", "shadow", "purified", "hearts_earned", "current_mega_level", "nickname", "background_slug" FROM \`pokemon_instance\`;--> statement-breakpoint
DROP TABLE \`pokemon_instance\`;--> statement-breakpoint
ALTER TABLE \`__new_pokemon_instance\` RENAME TO \`pokemon_instance\`;--> statement-breakpoint
PRAGMA foreign_keys=ON;`,
  "0004_empty_vapor": `-- Hand-edited after \`npm run db:generate\`, per 0000_baseline.sql's header
-- comment and the precedent in 0001_timestamps_to_epoch_ms.sql (an 11-table
-- rebuild with the same class of fixes). This migration widens the primary
-- key on five personal tables to include profile_id, retypes every
-- profile_id (and profile.id) from INTEGER to TEXT, and adds
-- app_settings.profile_id + profile.is_current. It also adds a new global
-- (non-profile-scoped) app_meta table and moves reference_data_version out of
-- the now-per-profile app_settings into it (a global value can no longer live
-- in app_settings, whose profile_id is NOT NULL with a REFERENCES profile(id)
-- FK) -- the WHERE key='reference_data_version' backfill runs before
-- app_settings is dropped so an upgrading device keeps its resync-skip marker.
-- Four hand-fixes were needed:
--
-- (1) Restored EVERY REFERENCES clause drizzle-kit's rebuild drops. These
-- columns are deliberately plain (no Drizzle \`.references()\`) in
-- schema/personal.ts because their targets live in schema/reference.ts,
-- excluded from drizzle-kit's schema path (see that file's header comment).
-- The set matches the current on-disk schema (0001's rebuild + 0002/0003 for
-- pokemon_instance): the reference-slug FKs (form/species/mega_variant/medal
-- slugs, player_progress_personal.current_level -> player_level.level,
-- pokemon_instance/form_background_personal.background_slug) AND every
-- profile_id -> profile(id). app_settings.profile_id's REFERENCES is new
-- (the column itself is new this migration).
--
-- (2) pokemon_instance's generated iv_percent column dropped from the
-- INSERT/SELECT column lists (SQLite rejects INSERTing a GENERATED column;
-- it's computed on read) -- same fix as 0002/0003.
--
-- (3) profile.is_current is a brand-new column, so it cannot be SELECTed
-- from the old profile table -- dropped from the INSERT/SELECT lists; every
-- pre-existing profile row lands is_current=0 (its column default). Setting
-- exactly one profile is_current=1 is Task 2's job (the UUID/seeding step).
--
-- (4) app_settings.profile_id is also brand-new (old app_settings was
-- (key, value) only), so the raw \`SELECT ... profile_id ... FROM app_settings\`
-- drizzle-kit emitted raises "no such column: profile_id". Replaced with
-- \`(SELECT id FROM profile LIMIT 1)\` so every pre-existing setting is carried
-- over onto the single existing profile (app_settings is rebuilt before
-- profile, so the old profile row is still present at that point). The
-- reference_data_version key is excluded here (WHERE key != ...) because it
-- moves to the global app_meta table instead -- keeping it out of the
-- per-profile app_settings avoids a duplicate copy that would otherwise tag
-- along on a future personal-data export.
--
-- Also fixed the multi-table PRAGMA-bracketing bug drizzle-kit hits on a
-- >1-table rebuild (see 0000_baseline.sql): it emitted \`foreign_keys=ON\`
-- after only the FIRST table. Moved it to bracket the whole file
-- (OFF at the top, ON at the very end). (Inert under this project's runner,
-- which toggles FK enforcement outside the migration transaction -- see
-- migrations.ts -- but kept correct to match every prior migration.)
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE \`app_meta\` (
	\`key\` text PRIMARY KEY NOT NULL,
	\`value\` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`__new_form_background_personal\` (
	\`form_slug\` text NOT NULL REFERENCES form(slug),
	\`profile_id\` text NOT NULL REFERENCES profile(id),
	\`achievement_field\` text NOT NULL,
	\`background_slug\` text NOT NULL REFERENCES backgrounds(slug),
	\`updated_at\` integer DEFAULT 0 NOT NULL,
	PRIMARY KEY(\`profile_id\`, \`form_slug\`, \`achievement_field\`, \`background_slug\`)
);
--> statement-breakpoint
INSERT INTO \`__new_form_background_personal\`("form_slug", "profile_id", "achievement_field", "background_slug", "updated_at") SELECT "form_slug", "profile_id", "achievement_field", "background_slug", "updated_at" FROM \`form_background_personal\`;--> statement-breakpoint
DROP TABLE \`form_background_personal\`;--> statement-breakpoint
ALTER TABLE \`__new_form_background_personal\` RENAME TO \`form_background_personal\`;--> statement-breakpoint
CREATE TABLE \`__new_app_settings\` (
	\`key\` text NOT NULL,
	\`profile_id\` text NOT NULL REFERENCES profile(id),
	\`value\` text NOT NULL,
	PRIMARY KEY(\`profile_id\`, \`key\`)
);
--> statement-breakpoint
INSERT INTO \`__new_app_settings\`("key", "profile_id", "value") SELECT "key", (SELECT id FROM profile LIMIT 1), "value" FROM \`app_settings\` WHERE "key" != 'reference_data_version';--> statement-breakpoint
INSERT INTO \`app_meta\` ("key", "value") SELECT "key", "value" FROM \`app_settings\` WHERE "key" = 'reference_data_version';--> statement-breakpoint
DROP TABLE \`app_settings\`;--> statement-breakpoint
ALTER TABLE \`__new_app_settings\` RENAME TO \`app_settings\`;--> statement-breakpoint
CREATE TABLE \`__new_form_personal\` (
	\`form_slug\` text NOT NULL REFERENCES form(slug),
	\`profile_id\` text NOT NULL REFERENCES profile(id),
	\`caught\` integer DEFAULT false NOT NULL,
	\`shiny\` integer DEFAULT false NOT NULL,
	\`floor\` integer DEFAULT false NOT NULL,
	\`four_star\` integer DEFAULT false NOT NULL,
	\`shundo\` integer DEFAULT false NOT NULL,
	\`lucky\` integer DEFAULT false NOT NULL,
	\`lucky_shiny\` integer DEFAULT false NOT NULL,
	\`lucky_floor\` integer DEFAULT false NOT NULL,
	\`lucky_four_star\` integer DEFAULT false NOT NULL,
	\`lucky_shundo\` integer DEFAULT false NOT NULL,
	\`shadow\` integer DEFAULT false NOT NULL,
	\`shadow_shiny\` integer DEFAULT false NOT NULL,
	\`shadow_floor\` integer DEFAULT false NOT NULL,
	\`shadow_four_star\` integer DEFAULT false NOT NULL,
	\`shadow_shundo\` integer DEFAULT false NOT NULL,
	\`dynamax\` integer DEFAULT false NOT NULL,
	\`dynamax_floor\` integer DEFAULT false NOT NULL,
	\`dynamax_shiny\` integer DEFAULT false NOT NULL,
	\`dynamax_four_star\` integer DEFAULT false NOT NULL,
	\`dynamax_shundo\` integer DEFAULT false NOT NULL,
	\`lucky_dynamax\` integer DEFAULT false NOT NULL,
	\`lucky_dynamax_floor\` integer DEFAULT false NOT NULL,
	\`lucky_dynamax_shiny\` integer DEFAULT false NOT NULL,
	\`lucky_dynamax_four_star\` integer DEFAULT false NOT NULL,
	\`lucky_dynamax_shundo\` integer DEFAULT false NOT NULL,
	\`best_shiny\` text,
	\`best_non_shiny\` text,
	\`best_lucky\` text,
	\`updated_at\` integer DEFAULT 0 NOT NULL,
	PRIMARY KEY(\`profile_id\`, \`form_slug\`),
	CONSTRAINT "form_personal_caught_bool" CHECK("__new_form_personal"."caught" IN (0, 1)),
	CONSTRAINT "form_personal_shiny_bool" CHECK("__new_form_personal"."shiny" IN (0, 1)),
	CONSTRAINT "form_personal_floor_bool" CHECK("__new_form_personal"."floor" IN (0, 1)),
	CONSTRAINT "form_personal_fourStar_bool" CHECK("__new_form_personal"."four_star" IN (0, 1)),
	CONSTRAINT "form_personal_shundo_bool" CHECK("__new_form_personal"."shundo" IN (0, 1)),
	CONSTRAINT "form_personal_lucky_bool" CHECK("__new_form_personal"."lucky" IN (0, 1)),
	CONSTRAINT "form_personal_luckyShiny_bool" CHECK("__new_form_personal"."lucky_shiny" IN (0, 1)),
	CONSTRAINT "form_personal_luckyFloor_bool" CHECK("__new_form_personal"."lucky_floor" IN (0, 1)),
	CONSTRAINT "form_personal_luckyFourStar_bool" CHECK("__new_form_personal"."lucky_four_star" IN (0, 1)),
	CONSTRAINT "form_personal_luckyShundo_bool" CHECK("__new_form_personal"."lucky_shundo" IN (0, 1)),
	CONSTRAINT "form_personal_shadow_bool" CHECK("__new_form_personal"."shadow" IN (0, 1)),
	CONSTRAINT "form_personal_shadowShiny_bool" CHECK("__new_form_personal"."shadow_shiny" IN (0, 1)),
	CONSTRAINT "form_personal_shadowFloor_bool" CHECK("__new_form_personal"."shadow_floor" IN (0, 1)),
	CONSTRAINT "form_personal_shadowFourStar_bool" CHECK("__new_form_personal"."shadow_four_star" IN (0, 1)),
	CONSTRAINT "form_personal_shadowShundo_bool" CHECK("__new_form_personal"."shadow_shundo" IN (0, 1)),
	CONSTRAINT "form_personal_dynamax_bool" CHECK("__new_form_personal"."dynamax" IN (0, 1)),
	CONSTRAINT "form_personal_dynamaxFloor_bool" CHECK("__new_form_personal"."dynamax_floor" IN (0, 1)),
	CONSTRAINT "form_personal_dynamaxShiny_bool" CHECK("__new_form_personal"."dynamax_shiny" IN (0, 1)),
	CONSTRAINT "form_personal_dynamaxFourStar_bool" CHECK("__new_form_personal"."dynamax_four_star" IN (0, 1)),
	CONSTRAINT "form_personal_dynamaxShundo_bool" CHECK("__new_form_personal"."dynamax_shundo" IN (0, 1)),
	CONSTRAINT "form_personal_luckyDynamax_bool" CHECK("__new_form_personal"."lucky_dynamax" IN (0, 1)),
	CONSTRAINT "form_personal_luckyDynamaxFloor_bool" CHECK("__new_form_personal"."lucky_dynamax_floor" IN (0, 1)),
	CONSTRAINT "form_personal_luckyDynamaxShiny_bool" CHECK("__new_form_personal"."lucky_dynamax_shiny" IN (0, 1)),
	CONSTRAINT "form_personal_luckyDynamaxFourStar_bool" CHECK("__new_form_personal"."lucky_dynamax_four_star" IN (0, 1)),
	CONSTRAINT "form_personal_luckyDynamaxShundo_bool" CHECK("__new_form_personal"."lucky_dynamax_shundo" IN (0, 1))
);
--> statement-breakpoint
INSERT INTO \`__new_form_personal\`("form_slug", "profile_id", "caught", "shiny", "floor", "four_star", "shundo", "lucky", "lucky_shiny", "lucky_floor", "lucky_four_star", "lucky_shundo", "shadow", "shadow_shiny", "shadow_floor", "shadow_four_star", "shadow_shundo", "dynamax", "dynamax_floor", "dynamax_shiny", "dynamax_four_star", "dynamax_shundo", "lucky_dynamax", "lucky_dynamax_floor", "lucky_dynamax_shiny", "lucky_dynamax_four_star", "lucky_dynamax_shundo", "best_shiny", "best_non_shiny", "best_lucky", "updated_at") SELECT "form_slug", "profile_id", "caught", "shiny", "floor", "four_star", "shundo", "lucky", "lucky_shiny", "lucky_floor", "lucky_four_star", "lucky_shundo", "shadow", "shadow_shiny", "shadow_floor", "shadow_four_star", "shadow_shundo", "dynamax", "dynamax_floor", "dynamax_shiny", "dynamax_four_star", "dynamax_shundo", "lucky_dynamax", "lucky_dynamax_floor", "lucky_dynamax_shiny", "lucky_dynamax_four_star", "lucky_dynamax_shundo", "best_shiny", "best_non_shiny", "best_lucky", "updated_at" FROM \`form_personal\`;--> statement-breakpoint
DROP TABLE \`form_personal\`;--> statement-breakpoint
ALTER TABLE \`__new_form_personal\` RENAME TO \`form_personal\`;--> statement-breakpoint
CREATE TABLE \`__new_medal_progress_personal\` (
	\`medal_slug\` text NOT NULL REFERENCES medal(slug),
	\`profile_id\` text NOT NULL REFERENCES profile(id),
	\`current_rank\` integer DEFAULT 0 NOT NULL,
	\`current_count\` integer DEFAULT 0 NOT NULL,
	\`updated_at\` integer NOT NULL,
	PRIMARY KEY(\`medal_slug\`, \`profile_id\`)
);
--> statement-breakpoint
INSERT INTO \`__new_medal_progress_personal\`("medal_slug", "profile_id", "current_rank", "current_count", "updated_at") SELECT "medal_slug", "profile_id", "current_rank", "current_count", "updated_at" FROM \`medal_progress_personal\`;--> statement-breakpoint
DROP TABLE \`medal_progress_personal\`;--> statement-breakpoint
ALTER TABLE \`__new_medal_progress_personal\` RENAME TO \`medal_progress_personal\`;--> statement-breakpoint
CREATE TABLE \`__new_mega_personal\` (
	\`mega_variant_slug\` text NOT NULL REFERENCES mega_variant(slug),
	\`profile_id\` text NOT NULL REFERENCES profile(id),
	\`evolved\` integer DEFAULT false NOT NULL,
	\`shiny_evolved\` integer DEFAULT false NOT NULL,
	\`updated_at\` integer DEFAULT 0 NOT NULL,
	PRIMARY KEY(\`profile_id\`, \`mega_variant_slug\`),
	CONSTRAINT "mega_personal_evolved_bool" CHECK("__new_mega_personal"."evolved" IN (0, 1)),
	CONSTRAINT "mega_personal_shinyEvolved_bool" CHECK("__new_mega_personal"."shiny_evolved" IN (0, 1))
);
--> statement-breakpoint
INSERT INTO \`__new_mega_personal\`("mega_variant_slug", "profile_id", "evolved", "shiny_evolved", "updated_at") SELECT "mega_variant_slug", "profile_id", "evolved", "shiny_evolved", "updated_at" FROM \`mega_personal\`;--> statement-breakpoint
DROP TABLE \`mega_personal\`;--> statement-breakpoint
ALTER TABLE \`__new_mega_personal\` RENAME TO \`mega_personal\`;--> statement-breakpoint
CREATE TABLE \`__new_player_progress_log\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	\`profile_id\` text NOT NULL REFERENCES profile(id),
	\`recorded_at\` integer NOT NULL,
	\`current_level\` integer,
	\`total_xp\` integer
);
--> statement-breakpoint
INSERT INTO \`__new_player_progress_log\`("id", "profile_id", "recorded_at", "current_level", "total_xp") SELECT "id", "profile_id", "recorded_at", "current_level", "total_xp" FROM \`player_progress_log\`;--> statement-breakpoint
DROP TABLE \`player_progress_log\`;--> statement-breakpoint
ALTER TABLE \`__new_player_progress_log\` RENAME TO \`player_progress_log\`;--> statement-breakpoint
CREATE TABLE \`__new_player_progress_personal\` (
	\`profile_id\` text PRIMARY KEY NOT NULL REFERENCES profile(id),
	\`current_level\` integer REFERENCES player_level(level),
	\`total_xp\` integer,
	\`updated_at\` integer NOT NULL
);
--> statement-breakpoint
INSERT INTO \`__new_player_progress_personal\`("profile_id", "current_level", "total_xp", "updated_at") SELECT "profile_id", "current_level", "total_xp", "updated_at" FROM \`player_progress_personal\`;--> statement-breakpoint
DROP TABLE \`player_progress_personal\`;--> statement-breakpoint
ALTER TABLE \`__new_player_progress_personal\` RENAME TO \`player_progress_personal\`;--> statement-breakpoint
CREATE TABLE \`__new_pokemon_instance\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	\`form_slug\` text NOT NULL REFERENCES form(slug),
	\`profile_id\` text NOT NULL REFERENCES profile(id),
	\`status\` text DEFAULT 'kept' NOT NULL,
	\`recorded_at\` integer NOT NULL,
	\`caught_at\` integer,
	\`updated_at\` integer NOT NULL,
	\`cp\` integer,
	\`iv_attack\` integer,
	\`iv_defense\` integer,
	\`iv_stamina\` integer,
	\`iv_percent\` real GENERATED ALWAYS AS (CASE WHEN iv_attack IS NOT NULL AND iv_defense IS NOT NULL AND iv_stamina IS NOT NULL THEN ROUND((iv_attack + iv_defense + iv_stamina) * 100.0 / 45, 1) ELSE NULL END) VIRTUAL,
	\`shiny\` integer DEFAULT false NOT NULL,
	\`lucky\` integer DEFAULT false NOT NULL,
	\`shadow\` integer DEFAULT false NOT NULL,
	\`purified\` integer DEFAULT false NOT NULL,
	\`dynamax\` integer DEFAULT false NOT NULL,
	\`received_via_trade\` integer DEFAULT false NOT NULL,
	\`hearts_earned\` integer,
	\`current_mega_level\` integer,
	\`nickname\` text,
	\`background_slug\` text REFERENCES backgrounds(slug),
	CONSTRAINT "pokemon_instance_shiny_bool" CHECK("__new_pokemon_instance"."shiny" IN (0, 1)),
	CONSTRAINT "pokemon_instance_lucky_bool" CHECK("__new_pokemon_instance"."lucky" IN (0, 1)),
	CONSTRAINT "pokemon_instance_shadow_bool" CHECK("__new_pokemon_instance"."shadow" IN (0, 1)),
	CONSTRAINT "pokemon_instance_purified_bool" CHECK("__new_pokemon_instance"."purified" IN (0, 1)),
	CONSTRAINT "pokemon_instance_dynamax_bool" CHECK("__new_pokemon_instance"."dynamax" IN (0, 1)),
	CONSTRAINT "pokemon_instance_receivedViaTrade_bool" CHECK("__new_pokemon_instance"."received_via_trade" IN (0, 1)),
	CONSTRAINT "pokemon_instance_status_enum" CHECK("__new_pokemon_instance"."status" IN ('kept', 'traded', 'released', 'evolved')),
	CONSTRAINT "pokemon_instance_iv_attack_range" CHECK("__new_pokemon_instance"."iv_attack" IS NULL OR ("__new_pokemon_instance"."iv_attack" >= 0 AND "__new_pokemon_instance"."iv_attack" <= 15)),
	CONSTRAINT "pokemon_instance_iv_defense_range" CHECK("__new_pokemon_instance"."iv_defense" IS NULL OR ("__new_pokemon_instance"."iv_defense" >= 0 AND "__new_pokemon_instance"."iv_defense" <= 15)),
	CONSTRAINT "pokemon_instance_iv_stamina_range" CHECK("__new_pokemon_instance"."iv_stamina" IS NULL OR ("__new_pokemon_instance"."iv_stamina" >= 0 AND "__new_pokemon_instance"."iv_stamina" <= 15))
);
--> statement-breakpoint
INSERT INTO \`__new_pokemon_instance\`("id", "form_slug", "profile_id", "status", "recorded_at", "caught_at", "updated_at", "cp", "iv_attack", "iv_defense", "iv_stamina", "shiny", "lucky", "shadow", "purified", "dynamax", "received_via_trade", "hearts_earned", "current_mega_level", "nickname", "background_slug") SELECT "id", "form_slug", "profile_id", "status", "recorded_at", "caught_at", "updated_at", "cp", "iv_attack", "iv_defense", "iv_stamina", "shiny", "lucky", "shadow", "purified", "dynamax", "received_via_trade", "hearts_earned", "current_mega_level", "nickname", "background_slug" FROM \`pokemon_instance\`;--> statement-breakpoint
DROP TABLE \`pokemon_instance\`;--> statement-breakpoint
ALTER TABLE \`__new_pokemon_instance\` RENAME TO \`pokemon_instance\`;--> statement-breakpoint
CREATE TABLE \`__new_profile\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`username\` text NOT NULL,
	\`friend_code\` text,
	\`is_current\` integer DEFAULT false NOT NULL,
	\`created_at\` integer NOT NULL
);
--> statement-breakpoint
INSERT INTO \`__new_profile\`("id", "username", "friend_code", "created_at") SELECT "id", "username", "friend_code", "created_at" FROM \`profile\`;--> statement-breakpoint
DROP TABLE \`profile\`;--> statement-breakpoint
ALTER TABLE \`__new_profile\` RENAME TO \`profile\`;--> statement-breakpoint
CREATE TABLE \`__new_species_personal\` (
	\`species_slug\` text NOT NULL REFERENCES species(slug),
	\`profile_id\` text NOT NULL REFERENCES profile(id),
	\`registered\` integer DEFAULT false NOT NULL,
	\`xxl\` integer DEFAULT false NOT NULL,
	\`xxs\` integer DEFAULT false NOT NULL,
	\`purified\` integer DEFAULT false NOT NULL,
	\`updated_at\` integer DEFAULT 0 NOT NULL,
	PRIMARY KEY(\`profile_id\`, \`species_slug\`),
	CONSTRAINT "species_personal_registered_bool" CHECK("__new_species_personal"."registered" IN (0, 1)),
	CONSTRAINT "species_personal_xxl_bool" CHECK("__new_species_personal"."xxl" IN (0, 1)),
	CONSTRAINT "species_personal_xxs_bool" CHECK("__new_species_personal"."xxs" IN (0, 1)),
	CONSTRAINT "species_personal_purified_bool" CHECK("__new_species_personal"."purified" IN (0, 1))
);
--> statement-breakpoint
INSERT INTO \`__new_species_personal\`("species_slug", "profile_id", "registered", "xxl", "xxs", "purified", "updated_at") SELECT "species_slug", "profile_id", "registered", "xxl", "xxs", "purified", "updated_at" FROM \`species_personal\`;--> statement-breakpoint
DROP TABLE \`species_personal\`;--> statement-breakpoint
ALTER TABLE \`__new_species_personal\` RENAME TO \`species_personal\`;--> statement-breakpoint
CREATE TABLE \`__new_tag\` (
	\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	\`profile_id\` text NOT NULL REFERENCES profile(id),
	\`name\` text NOT NULL
);
--> statement-breakpoint
INSERT INTO \`__new_tag\`("id", "profile_id", "name") SELECT "id", "profile_id", "name" FROM \`tag\`;--> statement-breakpoint
DROP TABLE \`tag\`;--> statement-breakpoint
ALTER TABLE \`__new_tag\` RENAME TO \`tag\`;--> statement-breakpoint
CREATE UNIQUE INDEX \`tag_profile_id_name_unique\` ON \`tag\` (\`profile_id\`,\`name\`);--> statement-breakpoint
PRAGMA foreign_keys=ON;`,
};
